### ISSUE TITLE
how to used in project? 

### ISSUE THREAD

**Issue by patel-pragnesh** [hansemannn/titanium-scanner#1]

**Comment by caspahouzer** [comment]
https://github.com/hansemannn/titanium-scanner/blob/master/example/app.js

**Comment by patel-pragnesh** [comment]
> https://github.com/hansemannn/titanium-scanner/blob/master/example/app.js

Hi . Thank buts without module how we access?

**Comment by hansemannn** [comment]
You can always build it from source, but I just compiled it for you: https://github.com/hansemannn/titanium-scanner/releases/tag/v1.0.0

**Comment by patel-pragnesh** [comment]
Thanks @hansemannn
