### ISSUE TITLE
Scanned docs rest in Scanner when abort

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-scanner#3]
When I cancel the scanner and re-open the scanner, the previous scans are still in the bottom left corner.

How can I reset the scanner on open?

**Comment by hansemannn** [comment]
You have to clear the native scanner instance [here](https://github.com/hansemannn/titanium-scanner/blob/master/Classes/TiScannerModule.m#L71), see https://stackoverflow.com/questions/63981386/clear-the-scanned-images-cache-in-vndocumentcamerascan-swift for reference

**Comment by caspahouzer** [comment]
That's the way I do. I create a complete fresh scanner instance on button click 

I thought it's enough but also tried to set the instance to null on cancel

```
Scanner.addEventListener('cancel', function () {
                    Ti.API.warn('Cancelled …');
                    Scanner = null;
                });
```

**Comment by hansemannn** [comment]
I mean on the native side :) E.g.
```objc
_scannerViewController.delegate = nil
_scannerViewController = nil
```
in each delegate: https://github.com/hansemannn/titanium-scanner/blob/master/Classes/TiScannerModule.m#L68-L86
